#!/bin/bash
# We won't check for root permission for it's in early stage and started by systemd.

title="Choose operating system"

[[ "${1}" == "-b" ]] && timeout="--timeout 7" || timeout="" 
[[ "${1}" == "-b" ]] && warn="Timeout in 7 seconds\n" || warn="" 
rm -f /tmp/bootArgs

echo "${timeout}"
echo " ????" >> /tmp/bootArgs
echo ' "Continue"' >> /tmp/bootArgs

efibootmgr | while read line; do
	if [[ "$line" =~ ^BootOrder ]]; then
		echo $line | sed -e "s/BootOrder: //g" > /tmp/bootOrder
	fi
	if [[ "$line" =~ ^Boot[0-9a-eA-E][0-9a-eA-E][0-9a-eA-E][0-9a-eA-E] ]]; then
		echo " "${line:4:4} >> /tmp/bootArgs
		echo ' "'$line'"' >> /tmp/bootArgs
	fi
done

bootOrder=$(cat /tmp/bootOrder)
answer=$(cat /tmp/bootArgs | xargs zenity ${timeout} --height 300 --width 500 --title "${title}" --list --text="Current Boot Order ${bootOrder}\n${warn}Reboot into:" --column="Boot NUM" --column="Desc")

if [[ "$answer" =~ [0-9a-eA-E][0-9a-eA-E][0-9a-eA-E][0-9a-eA-E] ]]; then
	echo "$answer"
	efibootmgr -n $answer
	systemctl reboot
else
	echo "Pass"
fi
